id: A4B1984B8
base_file: f72EF.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:38:34.540324
  last_modified_at: 2022-06-17 11:38:34.540326
