id: A4B1984B8
base_file: f49A4.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:38:34.534208
  last_modified_at: 2022-06-17 11:38:34.534213
