id: A4B1984B8
base_file: fCBDC.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:38:34.543234
  last_modified_at: 2022-06-17 11:38:34.543237
