id: A4B1984B8
base_file: f484D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:38:34.530371
  last_modified_at: 2022-06-17 11:38:34.530379
