id: A4B1984B8
base_file: fD3D5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:38:34.544375
  last_modified_at: 2022-06-17 11:38:34.544378
